nest_clinet_0616/src/org/kosa/nest/client/CommandLineInterface.java
nest_clinet_0616/src/org/kosa/nest/common/DatabaseUtil.java
nest_clinet_0616/src/org/kosa/nest/common/DbConfig.java
nest_clinet_0616/src/org/kosa/nest/model/AdminDao.java
nest_clinet_0616/src/org/kosa/nest/model/AdminVO.java
nest_clinet_0616/src/org/kosa/nest/model/FileDao.java
nest_clinet_0616/src/org/kosa/nest/model/FileVO.java
nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/client/CommandLineInterface.java
nest_server_0616/src/org/kosa/nest/model/AdminDao.java
nest_server_0616/src/org/kosa/nest/model/FileDao.java
nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java
nest_server_0616/src/org/kosa/nest/service/ServerUserService.java

개요
1. 모두가 공통적으로 사용하는 클래스인 DatabaseUtil, DbConfig, VO 등을 생성하였습니다.
2. 여러 기능이 있어 팀원들이 공통으로 작성해야 하는 클래스인 ClientService, ServerAdminService, ServerUserService 등의 클래스를 생성하여 이후 git 충돌을 최대한 방지하고자 하였습니다.

chore : nest_server와 nest_client 모두에 common, vo, dao 등의 공통 사용 및 구현 클래스 생성

---

nest_clinet_0616/src/org/kosa/nest/common/ClientRepoConfig.java
nest_server_0616/src/org/kosa/nest/common/ServerRepoConfig.java

feat : 클라이언트의 파일 저장 경로와 서버의 파일 저장 경로를 설정

feat : 클라이언트의 파일 저장 경로와 서버의 파일 저장 경로를 설정

---

nest_clinet_0616/src/org/kosa/nest/common/ClientConfig.java
nest_server_0616/src/org/kosa/nest/common/ServerConfig.java

개요
ServerConfig와 ClientConfig 파일 저장 경로를 System.getProperty()를 사용해 운영체제 독립적으로 변경하였습니다.

chore: ServerConfig와 ClientConfig 파일 저장 경로를 운영체제 독립적으로 변경

---

nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java

개요
서버 프로그램에서 네트워크 접속을 처리하여 명령어를 클라이언트로부터 입력받고,
명령어에 해당하는 결과물을 ServerUserService로부터 받아와
클라이언트에게 전송하는 기능을 NetworkWorker와 그 이너클래스 ReceiveWorker로 구현하였습니다.
ReceiveWorker는 Runnable 인터페이스를 적용하여 멀티스레드 환경에서 여러 유저가 접속하여도 처리할 수 있도록 했습니다

feat : NetworkWorker, ReceiveWorker 구현, 명령어를 client에게 전송 받고, 명령어에 따른 결과물을 client에게 출력

---

nest_server_0616/src/org/kosa/nest/model/FileDao.java
nest_server_0616/src/org/kosa/nest/model/FileVO.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java

feat : 서버측의 FileDao에 getFileinfoList() 메소드 추가, ServerAdminService에 findAllList() 추가

chore: 서버측의 FileVO에 title, tag, fileCreateTime만 넣은 생성자 추가

---

nest_server_0616/src/org/kosa/nest/exception/FileNotFoundException.java
nest_server_0616/src/org/kosa/nest/service/ServerUserService.java

개요
ServerUserService 의 download() 메서드
사용자에게 받은 다운로드 명령어에서 키워드를 추출하고
해당하는 키워드의 파일 정보를 FileDao로 부터 FileVO로 반환받는다
FileVO에 저장된 위치에 해당하는 파일이 없다면 FileNotFoundException 을 발생시킨다.
아주 기본적인 테스트만 함

Feat/soon hyeong server user service.download()

---

nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java

오류를 수정하고 컴파일 에러를 제거하기 위한 준비를 했습니다

fix : networkworker에서 oos가 생성되지 않은 문제 해결, 컴파일 에러 제거

---

nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java
nest_server_0616/src/org/kosa/nest/service/ServerUserService.java
nest_server_0616/src/org/kosa/nest/test/ServerAdminServiceRegisterTest.java

개요
남아있는 컴파일 에러를 수정하였습니다.
1. nest_client의 ClientService의 컴파일 에러를 수정하였습니다.
2. nest_server의 NetworkWorker의 컴파일 에러를 수정하였습니다.
3. nest_server의 ServerAdminService의 컴파일 에러를 수정하였습니다.
4. nest_server의 ServerUserService의 컴파일 에러를 수정하였습니다

chore : 남아있는 컴파일 에러 모두 수정

---

nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java

* 개요 *
이 PR은 ClientService, ServerAdminService에 help() 기능을 추가했습니다.
help 명령어를 입력하면 도움말이 나옵니다.
*구현 내용*
- ClientService에 help() 메서드를 추가하여, 사용 가능한 명령어 목록과 간단한 설명을 출력하도록 구현했습니다.
- 사용자가 help 명령어를 입력하면, CLI에 각 명령어와 기능 설명이 출력됩니다.
* 테스트 방법 * 
- CLI에 help 명령어를 입력하면 됩니다.

feat : help() 기능 추가

---

nest_clinet_0616/src/org/kosa/nest/CommandLineInterface.java
nest_clinet_0616/src/org/kosa/nest/NestMain.java
nest_clinet_0616/src/org/kosa/nest/service/ClientService.java

개요
chore : help 메서드 CLI에서 호출하도록 변경

chore : help 메서드 CLI에서 호출하도록 변경

---

nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java

개요
클라이언트에 안내 메시지 추가
- 다운로드 완료
- 삭제 완료
서버 네트워크 안내 메시지 추가
- IP에서 접속
- 명령어 확인
- 객체 전송 시작 완료
- 파일전송 시작/완료
서버 관리자 명령어 안내 메시지 추가
- 등록 완료
- 관리자 정보 업데이트 완료
- ...

feat: 클라이언트와 서버의 출력 메세지 추가, 수정

---

nest_clinet_0616/src/org/kosa/nest/CommandLineInterface.java
nest_clinet_0616/src/org/kosa/nest/network/ReceiveWorker.java
nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/client/CommandLineInterface.java
nest_server_0616/src/org/kosa/nest/model/FileDao.java
nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java
nest_server_0616/src/org/kosa/nest/service/ServerUserService.java

개요
기존에 메서드의 반환값으로 ArrayList를 사용하던 것을 List로 바꿈
List로 바꿈으로써 만약 다른 List구현체를 사용하게 되었을 때 더 유연한 개발을 할 수 있음(현재는 x)
테스트
프로그램 전체 실행시 문제 없이 잘 작동함

chore: 메서드의 반환값으로 ArrayList<FileVO> 대신 List<FileVO>를 사용함

---

nest_clinet_0616/src/org/kosa/nest/NestMain.java
nest_clinet_0616/src/org/kosa/nest/client/CommandLineInterface.java
nest_clinet_0616/src/org/kosa/nest/exception/NoCommandLineException.java

개요
Client에서 프로그램이 시작될 떄 명령어를 함께 받아오도록 수정
Main 함수의 args를 CommandLineInterface() 에 전달하여 명령어를 사용
이전에 사용하던 Scanner는 사용하지 않음
테스트
전체 프로그램 테스트 통과

feat : client에서 명령어를 Main 함수의 args로 입력받음

---

nest_clinet_0616/src/org/kosa/nest/NestMain.java
nest_clinet_0616/src/org/kosa/nest/network/ReceiveWorker.java
nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/NestServerMain.java

개요
javadoc 파일 편집과, main문 argument 사용 위한 수정 충돌 해결

fix : javadoc 파일 편집과, main문 argument 사용 위한 수정 충돌 해결

---

nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/model/FileDao.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java
nest_server_0616/src/org/kosa/nest/service/ServerUserService.java

개요  
이 PR은 CafeDao 인터페이스와 구현체에 카페 엔티티의 주석(comment) 기능을 추가합니다.  
관리자가 카페 정보에 메모나 설명을 남길 수 있도록 하여 데이터 관리의 유연성과 기록성을 높이기 위함입니다.  
구현 내용  
주석 추가 및 충돌 처리 
테스트 방법  
테스트 없음

Feat/beom jun set client/server file location

---

nest_server_0616/src/org/kosa/nest/TheadHandler/ThreadHandler.java
nest_server_0616/src/org/kosa/nest/command/Command.java
nest_server_0616/src/org/kosa/nest/command/user/DownloadCommand.java
nest_server_0616/src/org/kosa/nest/command/user/InfoCommand.java
nest_server_0616/src/org/kosa/nest/command/user/SearchCommand.java
nest_server_0616/src/org/kosa/nest/model/AdminDao.java
nest_server_0616/src/org/kosa/nest/model/FileDao.java
nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java

개요
ServerUserService에 command Pattern을 적용
구현 내용
ServerUserService 메서드 삭제, Command interface 작성하여 하위 클래스로 각 메서드 구현하도록 함.
이후 NetworkWorker에서 ServerUserService가 아닌 각 Command 클래스 사용
테스트
테스트 안함...

refactor : server user service에 command pattern을 적용

---

nest_clinet_0616/src/org/kosa/nest/client/CommandLineInterface.java
nest_clinet_0616/src/org/kosa/nest/network/ReceiveWorker.java
nest_clinet_0616/src/org/kosa/nest/service/ClientService.java
nest_server_0616/src/org/kosa/nest/command/Command.java
nest_server_0616/src/org/kosa/nest/service/ServerAdminService.java

개요
ServerAdminService에 command Pattern을 적용중
구현 내용
Command 인터페이스를 상속한 command 클래스 작성중 -> ServerAdminService의 메서드 를 클래스로 변경

refactor : ServerAdminService command 적용중

---

nest_server_0616/src/org/kosa/nest/model/AdminDao.java
nest_server_0616/src/org/kosa/nest/model/FileDao.java

개요
Object Pool Design Pattern 적용(DBCP)
구현내용
DatabasePoolManager 클래스에서 DataSource를 이용해 Dao에 DBCP 적용
테스트
login 명령으로 db 접근 테스트 완료

refactor : refactor : Object Pool Design Pattern FileDao에 적용(DBCP)

---

nest_server_0616/src/org/kosa/nest/network/NetworkWorker.java

chore : NetworkWorker 에러 메세지 수정

---

nest_server_0616/src/logback.xml

개요
feat : reflections 로그 삭제
구현내용
logback.xml 추가하여 logback 로그 나타나지 않도록 수정
테스트
프로그램 실행하여 로그 없는 것 확인

feat : reflections 로그 삭제
